#!/usr/bin/env python3
"""Emit one gate-training config per gate task built by make_gate_labels.py.

The sparsity sweep needs a gate per class, and they differ only in data_root
and name, so the configs are generated rather than hand-written. MobileNetV3-
large is the backbone: it is the best gate on both ships and planes in the
existing sweep, and at 0.56 GFLOPs/img its overhead term is negligible, which
keeps the measured savings attributable to sparsity rather than to gate cost.

Reads reports/gate_tasks.json, writes configs/experiments/_generated/gates/.
"""
from __future__ import annotations

import json
from pathlib import Path

TASKS = Path("reports/gate_tasks.json")
OUT = Path("configs/experiments/_generated/gates")

TEMPLATE = """# Generated by scripts/make_gate_configs.py -- do not edit by hand.
# Gate task: {task} (val p+ = {p_plus:.4f}, {n_pos} positive val tiles)
backbone: mobilenetv3_large_100
image_size: 256
batch_size: 128
num_workers: 8
epochs: 20
lr: 0.001
weight_decay: 0.0001
loss: bce
sampler: balanced
pos_neg_ratio: 0.25
amp: true
device: cuda:0
seed: 67
name: {name}
project: runs
data_root: {data_root}
train_split: train
val_split: val
use_wandb: false
wandb_project: cascaded-rs-detection
"""


def main() -> int:
    if not TASKS.exists():
        print(f"  missing {TASKS} -- run scripts/make_gate_labels.py --all first")
        return 1
    tasks = json.load(open(TASKS))
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for info in tasks:
        slug = info["task"].replace(" ", "_")
        name = f"gate_sweep_{slug}"
        path = OUT / f"{name}.yaml"
        path.write_text(TEMPLATE.format(
            task=info["task"],
            p_plus=info["val"]["p_plus"],
            n_pos=info["val"]["n_positive"],
            name=name,
            data_root=info["root"],
        ))
        written.append((name, info["val"]["p_plus"], str(path)))

    print(f"{'config':<34}{'val p+':>10}")
    for name, p, _ in written:
        print(f"{name:<34}{p:>10.4f}")
    print(f"\n  {len(written)} configs -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
