#!/usr/bin/env python3
"""Emit paper/generated_numbers.tex from reports/.

The draft carried its headline figures as hand-maintained \\newcommand values at
the top of main.tex, which is how it came to state a 3 pp mAP tolerance while the
code applied a 97 % relative one, and to hardcode HRSC2016's positive rate as
94 % when the labels say 97.9 %. Every number the manuscript quotes is generated
here instead, so a stale value is a build error rather than a silent one.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path("paper/generated_numbers.tex")
FIG = Path("reports/figures")


def fmt(v: float, places: int = 1) -> str:
    return f"{v:.{places}f}"


def main() -> int:
    summary = {d["domain"]: d for d in json.load(open(FIG / "savings_summary.json"))}
    ceiling = json.load(open(FIG / "sparsity_ceiling.json"))
    prior = json.load(open(FIG / "prior_work_prediction.json"))
    gap = json.load(open(FIG / "flops_latency_gap.json"))
    loss = json.load(open(Path("reports/object_loss_rate.json")))

    lines = [
        "% Generated by scripts/paper_numbers.py -- do not edit by hand.",
        "% Regenerate after any change under reports/.",
        "",
    ]

    def cmd(name: str, value: str) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    # --- cost constants ---------------------------------------------------
    cr = gap["cost_ratios"]
    cmd("detgflops", fmt(cr["detector_gflops"], 2))
    cmd("gategflops", fmt(cr["gate_gflops"], 2))
    cmd("detlatms", fmt(cr["detector_ms"]["1"] if "1" in cr["detector_ms"] else list(cr["detector_ms"].values())[0], 2))
    cmd("gatelatms", fmt(cr["gate_ms"]["1"] if "1" in cr["gate_ms"] else list(cr["gate_ms"].values())[0], 2))
    cmd("gflopsratio", fmt(100 * cr["g_flops"], 2))
    # The small detector used in the orthogonality section, measured rather than
    # taken from the vendor's figure at a different input size.
    _n = Path("reports/speed/yolo11n_obb.json")
    if _n.exists():
        cmd("detngflops", fmt(json.load(open(_n))["gflops_per_image"], 2))
    for key, name in (("batch 1", "one"), ("batch 128/16", "batched")):
        cmd(f"latratio{name}", fmt(100 * cr["g_latency"][key], 2))
    cmd("latratiofactor", fmt(cr["g_latency"]["batch 1"] / cr["g_flops"], 0))

    # --- per-domain savings ----------------------------------------------
    alias = {
        "DOTA-ships": "Ships", "DOTA-planes": "Planes",
        "DOTA-small_vehicle": "SmallVeh", "HRSC2016": "HRSC",
        "sweep/any": "AnyClass",
        "DOTA-ships/YOLO11n": "ShipsN",
        "OAN-joint/ships": "OANjoint",
        "Independent/ships-matched": "IndepMatched",
    }
    for domain, tag in alias.items():
        d = summary.get(domain)
        if not d:
            continue
        best = d["by_tolerance_rule"]["absolute"]
        cmd(f"posrate{tag}", fmt(100 * d["p_plus"]))
        cmd(f"save{tag}", fmt(100 * best["saved_detector_only"]))
        cmd(f"ceil{tag}", fmt(100 * (1 - d["p_plus"])))
        cmd(f"tpr{tag}", fmt(best["tpr"], 3))
        cmd(f"fpr{tag}", fmt(best["fpr"], 3))
        cmd(f"map{tag}", fmt(best["mAP@0.50"], 3))
        if d.get("full_pass_mAP@0.50") is not None:
            cmd(f"fullpass{tag}", fmt(d["full_pass_mAP@0.50"], 4))
        share = d["p_plus"] * (1 - best["tpr"]) / max(best["saved_detector_only"], 1e-9)
        cmd(f"recallshare{tag}", fmt(100 * share))
        for e in gap["domains"]:
            if e["domain"] == domain:
                cmd(f"latsave{tag}", fmt(100 * e["saved_latency[batch 1]"]))

    # --- sweep coverage ---------------------------------------------------
    ps = [c["positive_rate"] for c in ceiling]
    cmd("nGatingTasks", str(len(ceiling)))
    cmd("nOperatingPoints", str(sum(d["n_operating_points"] for d in summary.values())))
    cmd("posrateMin", fmt(100 * min(ps)))
    cmd("posrateMax", fmt(100 * max(ps)))
    zero = [c for c in ceiling if c["savings_pct"] < 2]
    cmd("nZeroSavingClasses", str(len(zero)))

    # --- prior work -------------------------------------------------------
    oan = prior["oan"]
    lo, hi = oan["predicted_lossless_removal_band"]
    cmd("oanEmptyLo", fmt(100 * lo))
    cmd("oanEmptyHi", fmt(100 * hi))
    cmd("oanMeasuredTrain", fmt(100 * prior["measured_empty_tile_rate"]["per_split"]["train"]["empty_rate"]))
    cmd("oanMeasuredVal", fmt(100 * prior["measured_empty_tile_rate"]["per_split"]["val"]["empty_rate"]))
    cmd("oanTimeSaved", fmt(100 * oan["table1_mean_time_saved"]))
    cmd("oanRemoval", fmt(100 * oan["operating_point_removal"], 0))
    cmd("oanConversion", fmt(oan["compute_to_wallclock_ratio"], 2))
    cmd("oanGaofenSkipped", fmt(100 * oan["gaofen2"]["patches_skipped"], 0))
    cmd("oanGaofenTime", fmt(100 * oan["gaofen2"]["time_saved"]))
    cmd("oanGaofenConversion", fmt(oan["gaofen2"]["compute_to_wallclock_ratio"], 2))

    # --- object loss at tau = 0.5 ----------------------------------------
    tag = {"DOTA-ships": "Ships", "DOTA-planes": "Planes", "DOTA-small_vehicle": "SmallVeh"}
    for row in loss:
        if abs(row["threshold"] - 0.5) < 1e-9 and row["dataset"] in tag:
            cmd(f"objloss{tag[row['dataset']]}", fmt(100 * row["loss_rate"]))

    # Gate ranking quality for the two head-to-head arms, computed from the
    # score files so the prose cannot drift from them.
    try:
        from sklearn.metrics import average_precision_score
        for path, tag in (("reports/oan/gate_oan_ships_val.jsonl", "OANjoint"),
                          ("reports/gate_scores/gate_mbv3large_val.jsonl", "IndepMatched")):
            fp = Path(path)
            if not fp.exists():
                continue
            y, pr = [], []
            for line in fp.open():
                row = json.loads(line)
                y.append(row["label"]); pr.append(row["prob"])
            if len(set(y)) > 1:
                cmd(f"prauc{tag}", fmt(average_precision_score(y, pr), 3))
    except ImportError:
        pass

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    n = sum(1 for l in lines if l.startswith("\\newcommand"))
    print(f"  wrote {OUT} with {n} generated values")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
