#!/usr/bin/env python3
"""Emit paper/generated_tables.tex from reports/, for the same reason as
scripts/paper_numbers.py: a table typed by hand drifts from the data.
"""
from __future__ import annotations

import glob
import json
import os
from pathlib import Path

OUT = Path("paper/generated_tables.tex")
FIG = Path("reports/figures")
SCORES = Path("reports/gate_sweep_scores")

# Arms reported in the fused-gate section rather than the sweep: they share
# DOTA-ships' tile population, so they duplicate its x-position in the envelope
# and are not distinct gating tasks.
CODESIGN_ARMS = {"OAN-joint/ships", "Independent/ships-matched"}

PRETTY = {
    "DOTA-ships": "ship (per-class det.)",
    "DOTA-planes": "plane (per-class det.)",
    "DOTA-small_vehicle": "small vehicle (per-class det.)",
    "HRSC2016": "HRSC2016 (zero-shot)",
}


def gate_pr_auc() -> dict[str, float]:
    try:
        from sklearn.metrics import average_precision_score
    except ImportError:
        return {}
    out = {}
    for f in sorted(glob.glob(str(SCORES / "*_val.jsonl"))):
        task = os.path.basename(f).replace("gate_sweep_", "").replace("_val.jsonl", "")
        y, p = [], []
        for line in open(f):
            r = json.loads(line)
            y.append(r["label"]); p.append(r["prob"])
        if len(set(y)) > 1:
            out[task.replace("_", " ")] = float(average_precision_score(y, p))
    return out


def main() -> int:
    summary = json.load(open(FIG / "savings_summary.json"))
    prauc = gate_pr_auc()
    gap = {e["domain"]: e for e in json.load(open(FIG / "flops_latency_gap.json"))["domains"]}

    rows = []
    for d in summary:
        best = d["by_tolerance_rule"]["absolute"]
        if not best:
            continue
        name = d["domain"]
        if name in CODESIGN_ARMS:
            continue
        if name.startswith("sweep/"):
            label = name[len("sweep/"):]
            key = label
        else:
            label = PRETTY.get(name, name)
            key = None
        share = d["p_plus"] * (1 - best["tpr"]) / max(best["saved_detector_only"], 1e-9)
        rows.append({
            "label": label.replace("_", " "),
            "p_plus": d["p_plus"],
            "prauc": prauc.get(key) if key else None,
            "saved": best["saved_detector_only"],
            "tpr": best["tpr"], "fpr": best["fpr"],
            "share": share,
            "lat": gap.get(name, {}).get("saved_latency[batch 1]"),
            "is_sweep": name.startswith("sweep/"),
        })
    rows.sort(key=lambda r: r["p_plus"])

    L = ["% Generated by scripts/paper_tables.py -- do not edit by hand.", ""]
    L += [
        r"\begin{table*}[!t]", r"\centering",
        r"\caption{Every gating task, ordered by positive-tile rate. \emph{Save} is "
        r"compute saved against running the detector on all tiles, at the $3$\,pp "
        r"mAP$@0.5$ budget. \emph{Charged} is the share of that saving which comes "
        r"from discarding target-bearing tiles rather than skipping empty ones. "
        r"\emph{Save (ms)} re-prices the same operating point in batch-$1$ latency. "
        r"Rows marked $\dagger$ use the shared sixteen-class detector; the rest are "
        r"the original per-class runs. Generated from \texttt{reports/}.}",
        r"\label{tab:sweep}", r"\small",
        r"\begin{tabular}{lrrrrrrr}", r"\toprule",
        r"Gating task & $p_+$ & PR-AUC & Save & TPR & FPR & Charged & Save (ms) \\",
        r"\midrule",
    ]
    for r in rows:
        dag = r"$\dagger$" if r["is_sweep"] else ""
        pr = f"{r['prauc']:.3f}" if r["prauc"] is not None else "---"
        lat = f"{100*r['lat']:.1f}\\,\\%" if r["lat"] is not None else "---"
        L.append(
            f"{r['label']}{dag} & {100*r['p_plus']:.1f}\\,\\% & {pr} & "
            f"{100*r['saved']:.1f}\\,\\% & {r['tpr']:.3f} & {r['fpr']:.3f} & "
            f"{100*r['share']:.0f}\\,\\% & {lat} \\\\"
        )
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print(f"  wrote {OUT} with {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
