#!/usr/bin/env bash
# Phase 3: OAN joint training vs an independently trained gate, matched budget.
#
# Both arms get 50 epochs and patience 50, because the existing ships baseline
# early-stopped at epoch 11-14 under patience 10 and comparing a 50-epoch joint
# model against it would confound co-design with training budget.
#
#   setsid nohup scripts/run_unattended_oan.sh > logs/unattended_oan.log 2>&1 </dev/null &

set -u
R="$(cd "$(dirname "$0")/.." && pwd)"
cd "$R"
PY="$R/.venv/bin/python"
DEV="${DEV:-1}"
LOGDIR="$R/logs/oan"; mkdir -p "$LOGDIR"
echo $$ > "$R/logs/unattended_oan.pid"
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

log "OAN runner started (pid $$) on cuda:$DEV"

# --- arm 1: joint OAN training -------------------------------------------
# Resolved after training from the marker train_oan.py writes; Ultralytics does
# not put the run at <project>/<name>.
resolve_oandir() {
  if [ -s "$R/runs/oan_last_save_dir.txt" ]; then
    cat "$R/runs/oan_last_save_dir.txt"
  else
    find "$R/runs" -maxdepth 5 -type d -name "oan_ships_lambda3" 2>/dev/null | head -1
  fi
}
OANDIR=$(resolve_oandir)
if [ -z "$OANDIR" ] || [ ! -f "$OANDIR/weights/best.pt" ]; then
  log "training OAN-joint (ships, lambda=3, 50 epochs)"
  $PY scripts/train_oan.py --data configs/datasets/dota_ships.yaml \
    --weights yolo11m-obb.pt --model-cfg yolo11m-obb.yaml \
    --epochs 50 --patience 50 --batch 16 --imgsz 1024 \
    --lambda-oan 3.0 --device "$DEV" --name oan_ships_lambda3 \
    > "$LOGDIR/train_oan_ships.log" 2>&1
  log "  exit $?"
else
  log "OAN-joint already trained"
fi

# --- arm 2: matched-budget plain detector --------------------------------
CTRLDIR="$R/runs/obb/runs/baseline_yolo11m_dota_ships_obb_p50"
if [ ! -f "$CTRLDIR/weights/best.pt" ]; then
  log "training matched control (plain YOLO11m-OBB ships, 50 epochs, patience 50)"
  cat > "$R/configs/experiments/_generated/baseline_yolo11m_ships_p50.yaml" <<CFG
# Generated by run_unattended_oan.sh: matched-budget control for the OAN arm.
family: yolo11
dataset: configs/datasets/dota_ships.yaml
task: obb
imgsz: 1024
epochs: 50
batch: 16
device: auto
seed: 67
project: runs
train_args:
  patience: 50
  amp: true
  half: false
models:
  - name: baseline_yolo11m_dota_ships_obb_p50
    weights: yolo11m-obb.pt
CFG
  $PY scripts/train_detector.py \
    --config configs/experiments/_generated/baseline_yolo11m_ships_p50.yaml \
    --device "$DEV" > "$LOGDIR/train_control_ships.log" 2>&1
  log "  exit $?"
else
  log "matched control already trained"
fi

# --- score the OAN gate ---------------------------------------------------
OANDIR=$(resolve_oandir)
log "OAN run dir resolved to: ${OANDIR:-<none>}"
OANW=$(ls "$OANDIR"/weights/best.pt 2>/dev/null | head -1)
if [ -n "$OANW" ]; then
  log "scoring tiles with the OAN head"
  $PY scripts/score_tiles_oan.py --weights "$OANW" \
    --data-root data/processed/dota_ships --split val \
    --out "$R/reports/oan/gate_oan_ships_val.jsonl" \
    --nc 1 --device "cuda:$DEV" > "$LOGDIR/score_oan.log" 2>&1
  log "  exit $?"
else
  log "no OAN weights; skipping scoring"
fi

log "OAN runner finished"
